name: "[Dev] Revise development workflow"
description: "This may update ./.github directory, ./Makefile, ./pyproject.toml etc."

title: "[Dev] "
labels: ["development", "brainstorming"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: textarea
    id: problem
    attributes:
      label: Issues of the current workflow
      placeholder: What is the problem?
    validations:
      required: true

  - type: textarea
    id: action
    attributes:
      label: Action items
      placeholder: How can we solve the issue?

  - type: checkboxes
    id: consent
    attributes:
      label: Checkbox
      description: checkbox to submit this question
      options:
        - label: I agree to follow [Code of Conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html) and to engage in discussion actively.
          required: true
