name: "[General] Question or no templates found"
description: "All questions regarding this project and the library, tags may be changed later"

title: "[Dev] "
labels: ["question", "brainstorming"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: textarea
    id: question
    attributes:
      label: Question
      placeholder: Please provide the summary.
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What tried
      description:  Please provide the script your tried, if this is regarding the library
      value: >
        import covsirphy as cs
        print(cs.__version__)
      render: python

  - type: textarea
    id: comment
    attributes:
      label: Additional comments regarding this issue
      placeholder: Additional comments, including background of the question
      value: NA

  - type: checkboxes
    id: consent
    attributes:
      label: Checkbox
      description: checkbox to submit this question
      options:
        - label: I agree to follow [Code of Conduct](https://lisphilar.github.io/covid19-sir/CODE_OF_CONDUCT.html)
          required: true
        - label: I agree to create a new issue with the other templates if developers request
          required: true
