name: Update test
description: This may update files in ./tests directory for pytest

title: "[Test] "
labels: ["development"]

body:
  - type: markdown
    attributes:
      value: Always welcome, CovsirPhy project is developed by a community of volunteers :)

  - type: textarea
    id: script-to-test
    attributes:
      label: Script to test
      description:  Please provide the script to test.
      placeholder: >
        import covsirphy as cs
      render: python
    validations:
      required: true

  - type: textarea
    id: comment
    attributes:
      label: Additional comments regarding this issue
      placeholder: Additional comments, if required
      value: NA
